jobs:
  include:
    - name: 'Typescript'
      language: node_js
      node_js: '13.1'
      install:
        - npm install
      script:
        - npm run jest:cov
      after_script:
        - npx codecov@3
      cache:
        directories:
          - ~/.npm
          - ~/.cache

    - name: 'Python'
      language: python
      python: 3.8
      install:
        - pip install pipenv
        - pipenv install --dev
        - pip install codecov
      script:
        - npm run pytest:cov
      after_success:
        - codecov