name: Tests

on: [push]

jobs:
  typescript-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - name: Run TypeScript tests
      - run: npm run jest:cov
      - name: Upload coverage
      - uses: codecov/codecov-action@v1
        env:
          CI: true

  python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - run:
         - pip install pipenv
         - pipenv install --dev
         - pip install codecov
      - name: Run Python tests
      - run: npm run pytest:cov
      - name: Upload coverage
      - uses: codecov/codecov-action@v1
        env:
          CI: true